// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function DeleteAPIKey():Promise<main.OperationResult>;

export function OpenProjectDialog():Promise<string>;

export function RemoveProject(arg1:string):Promise<main.OperationResult>;

export function RunPrompt(arg1:string):Promise<main.OperationResult>;

export function SaveAPIKey(arg1:string):Promise<main.OperationResult>;

export function SelectProject(arg1:string):Promise<main.OperationResult>;
