// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function DeleteAPIKey() {
  return window['go']['main']['App']['DeleteAPIKey']();
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RunPrompt(arg1) {
  return window['go']['main']['App']['RunPrompt'](arg1);
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}
